import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AccountInfo from "../components/AccountInfo";
import AirdropButton from "../components/AirdropButton";
import * as web3 from "@solana/web3.js";
import { useCallback, useEffect, useState } from "react";
import { useWallet, useConnection } from "@solana/wallet-adapter-react";
import SendButton from "../components/SendButton";

const Home: NextPage = () => {
  const [account, setAccount] = useState<web3.AccountInfo<Buffer> | null>(null);
  const { publicKey } = useWallet();
  const { connection } = useConnection();

  const getAccountInfo = useCallback(() => {
    if (!connection || !publicKey) {
      setAccount(null);
      return;
    }

    // get account info
    // account data is bytecode that needs to be deserialized
    // serialization and deserialization is program specific
    connection.getAccountInfo(publicKey).then((_account) => {
      setAccount(_account);
    });
  }, [connection, publicKey]);

  useEffect(() => getAccountInfo(), [connection, publicKey]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <div className="w-full md:w-1/2 mx-auto border rounded mt-16 p-4">
          <section className="mb-2">
            <AccountInfo
              solQuantity={(account?.lamports || 0) / web3.LAMPORTS_PER_SOL}
            />
          </section>
          <section className="">
            <AirdropButton onSuccess={getAccountInfo} />
            <SendButton onSuccess={getAccountInfo} />
          </section>
        </div>
      </main>

      <footer className="text-center mt-4">
        <a
          href="https://github.com/veewoo"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>Powered by </span>
          <span> VeeWoo</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
